from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('customers/add/', views.add_customer, name='add_customer'),
    path('services/', views.service_list, name='service_list'),
    path('services/add/', views.add_service, name='add_service'),
    path('services/edit/<int:service_id>/', views.edit_service, name='edit_service'),
    path('appointments/', views.appointment_list, name='appointment_list'),
    path('appointments/add/', views.add_appointment, name='add_appointment'),
    path('appointments/edit/<int:appointment_id>/', views.edit_appointment, name='edit_appointment'),
    path('employees/', views.employee_list, name='employee_list'),
    path('employees/add/', views.add_employee, name='add_employee'),
    path('employees/<int:employee_id>/edit/', views.edit_employee, name='edit_employee'),
    path('employees/<int:employee_id>/delete/', views.delete_employee, name='delete_employee'),
    path('settings/', views.settings, name='settings'),
    path('service-points/', views.service_points_list, name='service_points_list'),
    path('expenses/', views.expense_list, name='expense_list'),
    path('expenses/add/', views.add_expense, name='add_expense'),
    path('expenses/edit/<int:expense_id>/', views.edit_expense, name='edit_expense'),
    path('payrolls/', views.payroll_list, name='payroll_list'),
    path('payrolls/generate/', views.generate_payroll, name='generate_payroll'),
    path('revenue/', views.revenue_dashboard, name='revenue_dashboard'),
    path('branches/', views.branch_list, name='branch_list'),
    path('branches/add/', views.add_branch, name='add_branch'),
    path('branches/edit/<int:branch_id>/', views.edit_branch, name='edit_branch'),
    path('reports/', views.report_dashboard, name='report_dashboard'),
    path('reports/export/excel/', views.export_report_excel, name='export_report_excel'),
    path('reports/export/pdf/', views.export_report_pdf, name='export_report_pdf'),
    path('coupons/', views.coupon_list, name='coupon_list'),
    path('coupons/add/', views.add_coupon, name='add_coupon'),
    path('coupons/edit/<int:coupon_id>/', views.edit_coupon, name='edit_coupon'),
    path('appointments/complete/<int:appointment_id>/', views.complete_appointment, name='complete_appointment'),
    path('payroll/delete/<int:payroll_id>/', views.delete_payroll, name='delete_payroll'),
    path('send-reminders/', views.send_manual_reminders, name='send_manual_reminders'),
    path('promotions/', views.promotion_list, name='promotion_list'),
    path('promotions/new/', views.create_promotion, name='create_promotion'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('create-user/', views.create_user, name='create_user'),
    path('onboarding/', views.onboarding, name='onboarding'),
    path('roles/add/', views.add_role, name='add_role'),
    path('buy_product/', views.buy_product, name='buy_product'),
]