# Generated by Django 5.1.3 on 2025-06-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('UTILITIES', 'Utilities'), ('WAGES', 'Staff Wages'), ('PRODUCTS', 'Product Purchases'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
