# Generated by Django 5.1.3 on 2025-06-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_customer_address_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
    ]
