# Generated by Django 5.1.3 on 2025-06-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_service_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.appointment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='used_loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
