# Generated by Django 5.1.3 on 2025-06-17 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_payment_appointment_payment_used_loyalty_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('reminder', 'Reminder'), ('promo', 'Promotion')], max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('content', models.TextField()),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer')),
            ],
        ),
    ]
