# Generated by Django 5.1.3 on 2025-06-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0007_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='salon_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the role (e.g., Admin, Manager, CustomRole)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text="A description of the role's responsibilities", null=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions associated with this role', to='auth.permission')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='The role assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.role'),
        ),
    ]
