# Generated by Django 5.1.3 on 2025-06-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_user_groups_role_alter_user_role'),
    ]

    operations = [
    ]
