# Generated by Django 5.1.3 on 2025-06-18 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_customer_business_customer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.business'),
        ),
    ]
