# Generated by Django 5.1.3 on 2025-06-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='standard_haircut_points',
            field=models.FloatField(default=1, help_text='Points awarded per completed haircut for all employees'),
        ),
    ]
