# Generated by Django 5.1.3 on 2025-06-19 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_business_standard_haircut_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ServicePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_points', models.FloatField(default=0, help_text='Loyalty points awarded to customer for this service')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.business')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.service')),
            ],
            options={
                'unique_together': {('service', 'branch', 'business')},
            },
        ),
    ]
