# Generated by Django 5.1.3 on 2025-06-19 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='additional_payments', to='system.service'),
        ),
        migrations.AddField(
            model_name='payment',
            name='products',
            field=models.ManyToManyField(blank=True, to='system.product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.customer'),
        ),
    ]
