# Generated by Django 5.1.3 on 2025-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_payment_additional_services_payment_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='loyalty_point_value',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Monetary value of one customer loyalty point in UGX', max_digits=10),
        ),
    ]
