# Generated by Django 5.1.3 on 2025-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_business_loyalty_point_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicepoints',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicepoints',
            name='employee_points',
            field=models.FloatField(default=1, help_text='Employee performance points awarded for this service at this branch'),
        ),
        migrations.AlterField(
            model_name='servicepoints',
            name='loyalty_points',
            field=models.DecimalField(decimal_places=1, help_text='Customer loyalty points awarded for this service at this branch', max_digits=10),
        ),
    ]
